//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class localitymaster
    {
        public int LocalityId { get; set; }
        public string LocalityName { get; set; }
        public Nullable<int> StoreId1 { get; set; }
        public Nullable<int> StoreId2 { get; set; }
        public Nullable<int> StoreId3 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
