//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class menusetupmaster
    {
        public int id { get; set; }
        public Nullable<int> menuid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    }
}
