//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordermaster
    {
        public int OrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> LoginId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TotalGST { get; set; }
        public Nullable<decimal> TotalDeliveryCharge { get; set; }
        public string TranactionId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
