//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionmaster
    {
        public int Id { get; set; }
        public Nullable<int> LoginId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string TransactionId { get; set; }
        public string PaymentId { get; set; }
        public string PaymentOrderId { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
